In [81]:
import numpy as np

In [82]:
a=np.array([1,2,3]) #creating a numpy array
b=np.array([4,5,6])

In [83]:
a,b  #printing number of numpy arrays

(array([1, 2, 3]), array([4, 5, 6]))

In [84]:
type(a)

numpy.ndarray

In [85]:
a

array([1, 2, 3])

In [86]:
b

array([4, 5, 6])

In [87]:
a/b

array([0.25, 0.4 , 0.5 ])

In [88]:
a*b

array([ 4, 10, 18])

In [89]:
a+b

array([5, 7, 9])

In [90]:
print(a+1)

[2 3 4]


#Numpy Subsetting

In [91]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [92]:
a[5]

6

In [93]:
a[0],a[2]

(1, 3)

In [94]:
a[np.random.randint(0,8)]

1

In [95]:
a[2]

3

In [96]:
a>23

array([False, False, False, False, False, False, False, False, False])

In [97]:
a>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [98]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [99]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a[0:1]

array([1])

In [102]:
a[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [103]:
a[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [104]:
a[5:-1]

array([6, 7, 8])

#Numpy Basic Stats

In [105]:
np.mean(a)

5.0

In [107]:
c=np.append(a,[15,16,17])
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 15, 16, 17])

In [108]:
np.median(a)

5.0

In [111]:
np.sum(a)

45

In [113]:
np.min(a)

1

In [114]:
np.max(a)

9

In [117]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.percentile(a,50)

5.0

#Some ways to create numpy arrays

In [120]:
np.array([1,2,3])

array([1, 2, 3])

In [123]:
a=np.array([[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [125]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [127]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [130]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [137]:
b=np.linspace(-40,40,100)

#Some Important Attributes

In [133]:
a.shape

(2, 3)

In [134]:
a.ndim

2

In [138]:
b.size

100

In [139]:
a.itemsize

8

In [140]:
a.dtype

dtype('int64')

In [141]:
a.astype

<function ndarray.astype>

#Generating Random Datas

In [143]:
np.random.random() #get random numbers between 1 and 0

0.0380363086052703

In [148]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [151]:
np.random.uniform(0,100)

30.233257263183976

In [152]:
np.random.randint(1,10)

<function RandomState.randint>

In [153]:
np.argmax(a)  #getting the index of random int

2

#2D numpy array

In [155]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [156]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [157]:
a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [161]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])